version: '3'

services:

  cliente-sistema:
    image: 'cliente:sistema'
    build:
      context: ../cliente-sistema
      dockerfile: Dockerfile
    container_name: 'cliente'
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/backend
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop
    networks:
      - backend

  estoque-sistema:
    image: 'estoque:sistema'
    build:
      context: ../estoque-sistema
      dockerfile: Dockerfile
    container_name: 'estoque'
    depends_on:
      - db
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/backend
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop
    networks:
      - backend

  pagamento-sistema:
    image: 'pagamento:sistema'
    build:
      context: ../pagamento-sistema
      dockerfile: Dockerfile
    container_name: 'pagamento'
    depends_on:
      - db
    ports:
      - "8082:8082"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/backend
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop
    networks:
      - backend

  pedido-sistema:
    image: 'pedido:sistema'
    build:
      context: ../pedido-sistema
      dockerfile: Dockerfile
    container_name: 'pedido'
    depends_on:
      - db
    ports:
      - "8083:8083"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/backend
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop
    networks:
      - backend

  produto-sistema:
    image: 'produto:sistema'
    build:
      context: ../produto-sistema
      dockerfile: Dockerfile
    container_name: 'produto'
    depends_on:
      - db
    ports:
      - "8084:8084"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/backend
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop
    networks:
      - backend

  db:
    image: 'postgres:latest'
    container_name: 'database'
    command: ["postgres", "-c", "log_statement=all"]
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=backend
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - backend
    
networks:
  backend:

volumes:
  db_data: